/* FIFA Prediction Pro — players.js  (GENERATED by build-players.mjs)
   Champion-star asset layer: one marquee player per WC2026 team, resolved to an
   IMMUTABLE upload.wikimedia.org photo + attribution at build time, plus a static
   TEAM_META map (iso2 for flagcdn flags, espnAbbr for ESPN crests).
   UMD; zero dependencies; browser + node safe. NO runtime API calls.

   PLAYERS[team]   = { star, photo?, credit? }   // photo omitted if unresolved
   TEAM_META[team] = { iso2, espnAbbr }          // flagcdn + ESPN abbreviations
   Flag:  https://flagcdn.com/{iso2}.svg   (circle: circle-flags/flags/{iso2}.svg)
   Crest: https://a.espncdn.com/i/teamlogos/countries/500/{espnAbbr}.png
*/
(function (root, factory) {
  if (typeof module !== 'undefined') module.exports = factory();
  else { var m = factory(); root.PLAYERS = m.PLAYERS; root.TEAM_META = m.TEAM_META; }
})(typeof self !== 'undefined' ? self : this, function () {
  var PLAYERS = {
    "Czech Rep.": {
      "star": "Patrik Schick",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/2020-03-10_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League_Achtelfinale%2C_RB_Leipzig_-_Tottenham_Hotspur_1DX_3672_by_Stepro.jpg/500px-2020-03-10_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League_Achtelfinale%2C_RB_Leipzig_-_Tottenham_Hotspur_1DX_3672_by_Stepro.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Mexico": {
      "star": "Santiago Giménez",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Santiago_Gim%C3%A9nez.png/500px-Santiago_Gim%C3%A9nez.png",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "South Korea": {
      "star": "Son Heung-min",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/BFA_2023_-2_Heung-Min_Son_%28cropped%29.jpg/500px-BFA_2023_-2_Heung-Min_Son_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "South Africa": {
      "star": "Percy Tau",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/f/f7/Percy_Tau_in_2019_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Qatar": {
      "star": "Akram Afif",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Qatar_v_Lebanon_%2837%29_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Switzerland": {
      "star": "Granit Xhaka",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Granit_Xhaka_%28cropped%29.jpg/500px-Granit_Xhaka_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Canada": {
      "star": "Alphonso Davies",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Alphonso_Davies_in_2022.jpg/500px-Alphonso_Davies_in_2022.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Bosnia & Herz.": {
      "star": "Edin Džeko",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/20150331_2026_AUT_BIH_2177_Edin_D%C5%BEeko_%28cropped%29.jpg/500px-20150331_2026_AUT_BIH_2177_Edin_D%C5%BEeko_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Brazil": {
      "star": "Vinícius Júnior",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/2023_05_06_Final_de_la_Copa_del_Rey_-_52879242230_%28cropped%29.jpg/500px-2023_05_06_Final_de_la_Copa_del_Rey_-_52879242230_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Morocco": {
      "star": "Achraf Hakimi",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Achraf_Hakimi_Morocco_v_Norway_7_June_2026-32.jpg/500px-Achraf_Hakimi_Morocco_v_Norway_7_June_2026-32.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Scotland": {
      "star": "Scott McTominay",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Scott_McTominay_Scotland_v_Bolivia_6_June_2026-41.jpg/500px-Scott_McTominay_Scotland_v_Bolivia_6_June_2026-41.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Haiti": {
      "star": "Duckens Nazon",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/2025_Iran_Football_Premier_League_Esteghlal_and_Zob_Ahan_football_match_3_Mehr_%28cropped%29.jpg/500px-2025_Iran_Football_Premier_League_Esteghlal_and_Zob_Ahan_football_match_3_Mehr_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Turkey": {
      "star": "Arda Güler",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/2/26/Derbide_Fenerbah%C3%A7e_Yedek_Oyuncu_Arda_G%C3%BCler_%282021-22_S%C3%BCper_Lig_-_Cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Paraguay": {
      "star": "Miguel Almirón",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Miguel_Almir%C3%B3n_Red_Bull_Atlanta_5.31.25-069_%28cropped%29.jpg/500px-Miguel_Almir%C3%B3n_Red_Bull_Atlanta_5.31.25-069_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Australia": {
      "star": "Mathew Ryan",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Ryan_rcl_asse_2425.png/500px-Ryan_rcl_asse_2425.png",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "United States": {
      "star": "Christian Pulisic",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Christian_Pulisic_USMNT_v_Belgium_Mar_28_2026-73_%28cropped%29.jpg/500px-Christian_Pulisic_USMNT_v_Belgium_Mar_28_2026-73_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Germany": {
      "star": "Jamal Musiala",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Jamal_Musiala_2022_%28cropped%29.jpg/500px-Jamal_Musiala_2022_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Ecuador": {
      "star": "Moisés Caicedo",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Moises_Caicedo_2022_%28cropped%29.jpg/500px-Moises_Caicedo_2022_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Ivory Coast": {
      "star": "Sébastien Haller",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/S%C3%A9bastien_Haller_2.jpg/500px-S%C3%A9bastien_Haller_2.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Curacao": {
      "star": "Leandro Bacuna",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Leandro_Bacuna.jpg/500px-Leandro_Bacuna.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Netherlands": {
      "star": "Virgil van Dijk",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/20160604_AUT_NED_8876_%28cropped%29.jpg/500px-20160604_AUT_NED_8876_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Sweden": {
      "star": "Alexander Isak",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Alexander_Isak_-_Sweden_-_Greece21_%28cropped%29.jpg/500px-Alexander_Isak_-_Sweden_-_Greece21_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Japan": {
      "star": "Takefusa Kubo",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Takefusa_Kubo_2019.png/500px-Takefusa_Kubo_2019.png",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Tunisia": {
      "star": "Hannibal Mejbri",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Hannibal_Mejbri_26042025_%281%29.jpg/500px-Hannibal_Mejbri_26042025_%281%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Belgium": {
      "star": "Kevin De Bruyne",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg/500px-Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Iran": {
      "star": "Mehdi Taremi",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/7/74/Iran_-_Japan%2C_AFC_Asian_Cup_2019_42_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Egypt": {
      "star": "Mohamed Salah",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Mohamed_Salah_2018.jpg/500px-Mohamed_Salah_2018.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "New Zealand": {
      "star": "Chris Wood",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Chris_Wood_%28cropped%29.jpg/500px-Chris_Wood_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Spain": {
      "star": "Lamine Yamal",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Lamine_Yamal_in_2025.jpg/500px-Lamine_Yamal_in_2025.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Uruguay": {
      "star": "Federico Valverde",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Federico_Valverde_2021_%28cropped%29.jpg/500px-Federico_Valverde_2021_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Saudi Arabia": {
      "star": "Salem Al-Dawsari",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Salem_Al-Dawsari_2018.jpg/500px-Salem_Al-Dawsari_2018.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Cape Verde": {
      "star": "Ryan Mendes",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Ryan_Mendes_%28LOSC_Lille%29.JPG/500px-Ryan_Mendes_%28LOSC_Lille%29.JPG",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "France": {
      "star": "Kylian Mbappé",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Picture_with_Mbapp%C3%A9_%28cropped_and_rotated%29.jpg/500px-Picture_with_Mbapp%C3%A9_%28cropped_and_rotated%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Senegal": {
      "star": "Sadio Mané",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Sadio_Mane_Al-Nassr.jpg/500px-Sadio_Mane_Al-Nassr.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Norway": {
      "star": "Erling Haaland",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg/500px-Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Iraq": {
      "star": "Aymen Hussein",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/7/78/4822953_AE7I9053_%28cropped2%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Argentina": {
      "star": "Lionel Messi",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Lionel_Messi_White_House_2026_%283x4_cropped%29.jpg/500px-Lionel_Messi_White_House_2026_%283x4_cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Austria": {
      "star": "David Alaba",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/20180610_FIFA_Friendly_Match_Austria_vs._Brazil_David_Alaba_850_1632.jpg/500px-20180610_FIFA_Friendly_Match_Austria_vs._Brazil_David_Alaba_850_1632.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Jordan": {
      "star": "Musa Al-Taamari",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Al_taamari_asse_mhsc_2425.png/500px-Al_taamari_asse_mhsc_2425.png",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Algeria": {
      "star": "Riyad Mahrez",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Mahrez_2021.jpg/500px-Mahrez_2021.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Portugal": {
      "star": "Cristiano Ronaldo",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/President_Donald_Trump_meets_with_Cristiano_Ronaldo_in_the_Oval_Office_%2854933344262%29_%28cropped_and_rotated%29.jpg/500px-President_Donald_Trump_meets_with_Cristiano_Ronaldo_in_the_Oval_Office_%2854933344262%29_%28cropped_and_rotated%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Colombia": {
      "star": "Luis Díaz",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/FC_RB_Salzburg_gegen_FC_Bayern_M%C3%BCnchen_%282026-01-06_Testspiel%29_40_%28Luiz_D%C3%ADaz%29.jpg/500px-FC_RB_Salzburg_gegen_FC_Bayern_M%C3%BCnchen_%282026-01-06_Testspiel%29_40_%28Luiz_D%C3%ADaz%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "DR Congo": {
      "star": "Yoane Wissa",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/CAN_2023RD_Congo_2-1_Guin%C3%A9e_9939_%28cropped%29.jpg/500px-CAN_2023RD_Congo_2-1_Guin%C3%A9e_9939_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Uzbekistan": {
      "star": "Eldor Shomurodov",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Eldor_Shomurodov_14_%C4%B0stanbul_Ba%C5%9Fak%C5%9Fehir_FK_20250731_%2810%29_%28cropped%29.jpg/500px-Eldor_Shomurodov_14_%C4%B0stanbul_Ba%C5%9Fak%C5%9Fehir_FK_20250731_%2810%29_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "England": {
      "star": "Jude Bellingham",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Jude_Bellingham_-_240422_190551-2_%28cropped%29.jpg/500px-25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Jude_Bellingham_-_240422_190551-2_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Croatia": {
      "star": "Luka Modrić",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Ofrenda_de_la_Liga_y_la_Champions-57-L.Mill%C3%A1n_%2852109310843%29_%28Luka_Modri%C4%87%29.jpg/500px-Ofrenda_de_la_Liga_y_la_Champions-57-L.Mill%C3%A1n_%2852109310843%29_%28Luka_Modri%C4%87%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Ghana": {
      "star": "Mohammed Kudus",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Mohammed_Kudus_of_West_Ham_United.jpeg/500px-Mohammed_Kudus_of_West_Ham_United.jpeg",
      "credit": "Wikimedia Commons / CC BY-SA"
    },
    "Panama": {
      "star": "Adalberto Carrasquilla",
      "photo": "https://upload.wikimedia.org/wikipedia/commons/d/dc/Inter_Miami_CF_3-1_UNAM_%286_August_2025%29_27_%28cropped%29.jpg",
      "credit": "Wikimedia Commons / CC BY-SA"
    }
  };

  var TEAM_META = {
    "Czech Rep.": {
      "iso2": "cz",
      "espnAbbr": "cze"
    },
    "Mexico": {
      "iso2": "mx",
      "espnAbbr": "mex"
    },
    "South Korea": {
      "iso2": "kr",
      "espnAbbr": "kors"
    },
    "South Africa": {
      "iso2": "za",
      "espnAbbr": "rsa"
    },
    "Qatar": {
      "iso2": "qa",
      "espnAbbr": "qat"
    },
    "Switzerland": {
      "iso2": "ch",
      "espnAbbr": "sui"
    },
    "Canada": {
      "iso2": "ca",
      "espnAbbr": "can"
    },
    "Bosnia & Herz.": {
      "iso2": "ba",
      "espnAbbr": "bih"
    },
    "Brazil": {
      "iso2": "br",
      "espnAbbr": "bra"
    },
    "Morocco": {
      "iso2": "ma",
      "espnAbbr": "mar"
    },
    "Scotland": {
      "iso2": "gb-sct",
      "espnAbbr": "sco"
    },
    "Haiti": {
      "iso2": "ht",
      "espnAbbr": "hai"
    },
    "Turkey": {
      "iso2": "tr",
      "espnAbbr": "tur"
    },
    "Paraguay": {
      "iso2": "py",
      "espnAbbr": "par"
    },
    "Australia": {
      "iso2": "au",
      "espnAbbr": "aus"
    },
    "United States": {
      "iso2": "us",
      "espnAbbr": "usa"
    },
    "Germany": {
      "iso2": "de",
      "espnAbbr": "ger"
    },
    "Ecuador": {
      "iso2": "ec",
      "espnAbbr": "ecu"
    },
    "Ivory Coast": {
      "iso2": "ci",
      "espnAbbr": "civ"
    },
    "Curacao": {
      "iso2": "cw",
      "espnAbbr": "cuw"
    },
    "Netherlands": {
      "iso2": "nl",
      "espnAbbr": "ned"
    },
    "Sweden": {
      "iso2": "se",
      "espnAbbr": "swe"
    },
    "Japan": {
      "iso2": "jp",
      "espnAbbr": "jpn"
    },
    "Tunisia": {
      "iso2": "tn",
      "espnAbbr": "tun"
    },
    "Belgium": {
      "iso2": "be",
      "espnAbbr": "bel"
    },
    "Iran": {
      "iso2": "ir",
      "espnAbbr": "irn"
    },
    "Egypt": {
      "iso2": "eg",
      "espnAbbr": "egy"
    },
    "New Zealand": {
      "iso2": "nz",
      "espnAbbr": "nzl"
    },
    "Spain": {
      "iso2": "es",
      "espnAbbr": "esp"
    },
    "Uruguay": {
      "iso2": "uy",
      "espnAbbr": "uru"
    },
    "Saudi Arabia": {
      "iso2": "sa",
      "espnAbbr": "ksa"
    },
    "Cape Verde": {
      "iso2": "cv",
      "espnAbbr": "cpv"
    },
    "France": {
      "iso2": "fr",
      "espnAbbr": "fra"
    },
    "Senegal": {
      "iso2": "sn",
      "espnAbbr": "sen"
    },
    "Norway": {
      "iso2": "no",
      "espnAbbr": "nor"
    },
    "Iraq": {
      "iso2": "iq",
      "espnAbbr": "irq"
    },
    "Argentina": {
      "iso2": "ar",
      "espnAbbr": "arg"
    },
    "Austria": {
      "iso2": "at",
      "espnAbbr": "aut"
    },
    "Jordan": {
      "iso2": "jo",
      "espnAbbr": "jor"
    },
    "Algeria": {
      "iso2": "dz",
      "espnAbbr": "alg"
    },
    "Portugal": {
      "iso2": "pt",
      "espnAbbr": "por"
    },
    "Colombia": {
      "iso2": "co",
      "espnAbbr": "col"
    },
    "DR Congo": {
      "iso2": "cd",
      "espnAbbr": "cod"
    },
    "Uzbekistan": {
      "iso2": "uz",
      "espnAbbr": "uzb"
    },
    "England": {
      "iso2": "gb-eng",
      "espnAbbr": "eng"
    },
    "Croatia": {
      "iso2": "hr",
      "espnAbbr": "cro"
    },
    "Ghana": {
      "iso2": "gh",
      "espnAbbr": "gha"
    },
    "Panama": {
      "iso2": "pa",
      "espnAbbr": "pan"
    }
  };

  return { PLAYERS: PLAYERS, TEAM_META: TEAM_META };
});
